name: jarvis_ktk
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: 10.7.0
  dropdown_button2: ^2.3.8
  dropdown_search: 6.0.0
  flutter_animate: 4.0.0
  fluttertoast: ^8.2.8
  file_picker: ^5.0.0
  intl: ^0.17.0
  dio: ^5.7.0
  mime: ^2.0.0
  http_parser: ^4.0.2
  flutter_secure_storage: ^9.2.2
  get_it: ^8.0.2
  provider: ^6.0.0
  json_annotation: ^4.9.0
  draggable_bottom_sheet: ^1.0.2

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/unit/
